version: "3"
services:
  api:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "127.0.0.1:5051:5050"
    volumes:
      - ./data:/app/data
  ocr:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      target: ocr
    volumes:
      - ./data:/app/data

  redis:
    image: "redis:5.0.14"
    command: redis-server
    ports:
      - "6479:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - testing
