version: "3"
services:
  api:
    init: true
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "5051:5050"
    volumes:
      - ./data:/app/data
  ocr:
    init: true
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
      target: ocr
    volumes:
      - ./data:/app/data

  redis:
    image: "redis:5.0.14"
    restart: unless-stopped
    command: redis-server
    ports:
      - "6479:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - testing
