version: '3'
services:
  server:
    init: true
    build:
      context: .
      dockerfile: Dockerfile_sever
    ports:
      - "5051:5050"
    volumes:
      - ./docker_volume:/app/docker_volume
    depends_on:
      # - mongo_paragraphs
      - redis_paragraphs
  extract_pdf_paragraphs:
    init: true
    build:
      context: .
      dockerfile: Dockerfile_extractor
    volumes:
      - ./docker_volume:/app/docker_volume
    depends_on:
      # - mongo_paragraphs
      - redis_paragraphs
  # mongo_paragraphs:
  #   image: "mongo:4.0.1"
  #   volumes:
  #     - ./db:/data/db
  #     - ./db/journal:/data/db/journal
  #   ports:
  #     - '29017-29019:27017-27019'
  redis_paragraphs:
    image: "redis:5.0.14"
    command: redis-server
    ports:
      - "6479:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
