version: "3"
services:
  api:
    init: true
    # stdin_open: true
    # tty: true
    # command: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - "127.0.0.1:5051:5050"
    volumes:
      - ./data:/app/data
  ocr:
    init: true
    build:
      context: .
      dockerfile: Dockerfile_ocr
    volumes:
      - ./data:/app/data
