version: '3'
services:
  server:
    init: true
    build:
      context: .
      dockerfile: Dockerfile_sever
    ports:
      - "127.0.0.1:5051:5050"
    volumes:
      - ./docker_volume:/app/docker_volume
  extract_pdf_paragraphs:
    init: true
    build:
      context: .
      dockerfile: Dockerfile_extractor
    volumes:
      - ./docker_volume:/app/docker_volume
